# Generated by Django 4.2.5 on 2023-09-29 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('videoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('videoName', models.CharField(max_length=250)),
                ('video', models.FileField(upload_to='videoFolder/')),
            ],
        ),
    ]
