# Generated by Django 4.2.5 on 2023-09-30 04:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensionApi', '0004_alter_videodata_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='file',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
