# Generated by Django 4.2.5 on 2023-09-30 04:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensionApi', '0005_videodata_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='file',
        ),
        migrations.AlterField(
            model_name='videodata',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
