# Generated by Django 4.2.5 on 2023-10-01 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extensionApi', '0008_remove_videodata_videoid_videodata_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='id',
        ),
        migrations.AddField(
            model_name='videodata',
            name='video_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
